# Generated by Django 2.0.4 on 2018-07-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='theme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogTheme'),
        ),
    ]
